sudo: required
language: generic
services:
  - docker


before_install:
  - docker build -t suksaggu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true suksaggu/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: ca-central-1
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ca-central-1-158316072815"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
